### ISSUE TITLE
Cache mount links dependent upon suboption ordering

### ISSUE THREAD

**Issue by iamthad** [patrickhoefler/dockerfilegraph#178]
```Dockerfile
FROM scratch AS foo

FROM scratch AS bar
RUN --mount=type=cache,from=foo,target=/mnt
```
renders as 
![Dockerfile test1](https://user-images.githubusercontent.com/2285761/195380934-69ee15d2-5783-44d6-85b9-ab62f0c3e331.png)

But
```Dockerfile
FROM scratch AS foo

FROM scratch AS bar
RUN --mount=type=cache,target=/mnt,from=foo
```

does not recognize the link between the stages and renders as

![zopfli_Dockerfile](https://user-images.githubusercontent.com/2285761/195381658-009f13b4-0b91-4a9a-bfa1-74d3e36384e3.png)

**Comment by patrickhoefler** [comment]
As always, thank you for the bug report 🙇🏼‍♂️

The fix is currently going through the CI pipeline, the bugfix version should roll out in a few minutes.
