### ISSUE TITLE
Include buildkit `mount=type=cache` relations.

### ISSUE THREAD

**Issue by hansbogert** [patrickhoefler/dockerfilegraph#19]
Would be awesome if we could see buildkit's `mount=type=cache` as edges. So take the running example in the README.md; imagine `current` using a cache with the following Dockfile directive:

```Dockerfile
RUN --mount=type=cache,from=builderbase,source=/go/pkg/mod/cache/,target=/go/pkg/mod/cache/

``` 

and this could be represented with a relation 

```dot
builderbase -> current [label="cache, from ...."]
```
Or the `(stage,cache directory)` tuple could be its own node in the graph.

**Comment by patrickhoefler** [comment]
Hey @hansbogert,

thanks for the great suggestion!

I already started working on a prototype to add the basic functionality. Unfortunately I ran into a Graphviz bug along the way, which delayed things slightly. I should have a PR ready soon though.

**Comment by patrickhoefler** [comment]
I just finished implementing the basic functionality. @hansbogert could you take a look at #23 – and ideally give it a try – and let me know if this works for you?

I didn't add the edge labels yet. I gave it a quick try, but the results were pretty ugly. If this is something you really need, please open a new issue and we can probably add this as a flag.

**Comment by hansbogert** [comment]
looked at it!. This is already helpful, but iiuc, the cache mount is a little more intricate, though I have to admit I don't all the edge cases.
Currently` the "from" option is taken as the node label,  however it is optional, in fact the `id` should be taken as reference, which is optional as well, but defaults to `target`. 

I'd advise to let a cache target be a distinct node in the graph. Stages which reference the target should obviously have an edge to that node.

**Comment by patrickhoefler** [comment]
Thanks for the feedback :)

I do agree that the currently proposed implementation is rather minimalistic. My reasoning behind it: At the moment, `dockerfilegraph` visualizes _build stages_ and _external images_ and their interdependencies. The `from` option of the `--mount=type=cache` refers to a _build stage_ –  or an _external image_, which is not mentioned in the [documentation](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache) but works anyway – which fits in nicely with `dockerfilegraph`'s current capabilities.

When the `from` option is omitted, the caching mechanism just creates an empty directory on the host system and uses that. This would be a completely new entity type in the visualization and a rather big conceptual update to `dockerfilegraph`.

For this reason, I would limit support in this first iteration to `RUN --mount=type=cache` instances where the `from` option is provided.

I'm totally open to considering new entity types like the caching directory you suggested. If you have a concrete use case for this, I'd kindly ask you to create a separate issue for this so we can discuss it further.

In the meantime, I'll go ahead and merge what we have so far in #23. We should be able to use this as a jumping-off point for future extensions :)

**Comment by hansbogert** [comment]
@patrickhoefler this is already awesome. Thanks
