### ISSUE TITLE
Support for ARM architecture

### ISSUE THREAD

**Issue by Ferror** [patrickhoefler/dockerfilegraph#192]
```
The darwin_arm64 architecture is not supported for the Dockerfilegraph
formula at this time. The darwin_amd64 binary may work in compatibility
mode, but it might not be fully supported.
```

**Comment by patrickhoefler** [comment]
Hey @Ferror, thanks for raising this issue 🙂

I have just released [v0.9.3](https://github.com/patrickhoefler/dockerfilegraph/releases/tag/v0.9.3) with experimental ARM64 support, could you please give it a try and see if it works for you?

**Comment by Ferror** [comment]
@patrickhoefler I checked it out for https://github.com/Sylius/Sylius-Standard and it works. Thank you <3

**Comment by patrickhoefler** [comment]
Glad to hear it, you're very welcome 🙂
