### ISSUE TITLE
Better handling of large graphs

### ISSUE THREAD

**Issue by ebekebe** [patrickhoefler/dockerfilegraph#258]
Hi, thank you for this excellent tool. I used it to visualize a huge Dockerfile with many stages. While doing so, I wished for a couple of extra options.
But here is the result out of the box:

<img width="339" alt="Screenshot 2023-01-26 at 11 24 34" src="https://user-images.githubusercontent.com/5716819/214813681-817fdfd7-dd24-44fc-895c-bd8250b41f2c.png">

I would like to see a way of grouping multiple `COPY --from=..` arrows into one arrow only to improve readability. I manually edited the canon file to add `concentrate=true`, but this overlays `FROM ...` and `COPY ...`, so they aren't traceable anymore.

If grouping would be more intelligent, I think dashing / coloring the line for e.g. `COPY --from=...` would make it even more readable as I don't have to look to closely at the arrow heads.

Finally, I would like to see svg export. I am exporting to canon currently and execute dot afterwards.

My workaround is this dockerfile, which when build with `docker build -o . .` exports the result into the current directory:

```Dockerfile
FROM ghcr.io/patrickhoefler/dockerfilegraph:alpine AS build
WORKDIR /workspace
COPY the-dockerfile .
RUN /dockerfilegraph --filename the-dockerfile --output canon
RUN <Dockerfile.canon sed 's/rankdir=LR/rankdir=LR,concentrate=true/g' >Dockerfile.canon.patch
RUN dot -Tsvg Dockerfile.canon.patch -o Dockerfile.svg

FROM scratch
COPY --from=build /workspace/Dockerfile.svg /Dockerfile.svg
```

**Comment by patrickhoefler** [comment]
Hey Benjamin, thank you for your kind words and your feedback 🙂

I've just released [v0.11.0](https://github.com/patrickhoefler/dockerfilegraph/releases/tag/v0.11.0) including an SVG export flag.

I also like the idea of "concentrating" the edges and different line styles! I will look into this and let you know once I have something.

**Comment by patrickhoefler** [comment]
> I think dashing / coloring the line for e.g. `COPY --from=...` would make it even more readable as I don't have to look to closely at the arrow heads.

Done! [v0.12.0](https://github.com/patrickhoefler/dockerfilegraph/releases/tag/v0.12.0) has been released, and you can now tell just from the edge style if it's a `FROM`, `COPY` or `RUN` operation 🙂

I'm currently looking into the `concentrate` flag, let's see how that goes ...

**Comment by patrickhoefler** [comment]
Hello again!

[v0.13.0](https://github.com/patrickhoefler/dockerfilegraph/releases/tag/v0.13.0) has just been released, and it adds the `--concentrate` flag.

You should now be able to just run `dockerfilegraph -c -o svg` and already achieve a much better result.

As a last step, I will also add an [--unflatten](https://graphviz.org/docs/cli/unflatten/) flag that should improve your use case even further.

Let me know how this works for you!

**Comment by ebekebe** [comment]
Thank you Patrick for implementing it in such a short time. I just tried it out and there are again a couple of things that could be improved. However, having the the dotted/dashed lines is a game changer and makes the output readable for our case.

I will create a follow up ticket with the rendering and my findings.
