### ISSUE TITLE
Re-running on the same Dockerfile causes PDF file to change

### ISSUE THREAD

**Issue by jamesone** [patrickhoefler/dockerfilegraph#331]
I have committed and pushed the Dockerfile.pdf to my git repo. 

Now when I run the same command on the same Dockerfile, there are changes in git. 

```
docker run \
  --rm \
  --user "$(id -u):$(id -g)" \
  --workdir /workspace \
  --volume "$(pwd)":/workspace \
  ghcr.io/patrickhoefler/dockerfilegraph:alpine
  ```
  
  It's also worth noting that I move the generated .PDF to another directory after the command is done:
  
  ```
  mv Dockerfile.pdf ./docs/
  ```
  
Do you know why the Dockerfile.pdf is changing even though my Dockerfile has not? Could the library include a timestamp? 

Not sure if this helps at all, but the binary changed near the bottom of the RAW binary code.

Before binary:
```
stream
x�5�=�0����u1yS?ZݺH���!h�B1����r�q����/sP����
�)�W�_�a�7�B��m� Vׁ��^;D���%T$9���e-9�qj�~M�3q|�8��d�Vy��-��'�RAR���#��F���mM �hW�G_'a4�
endstream
endobj
```

After binary:
```
stream
x�5�=�0����u1yS?P�E�.R:�t�P��8�߷F��p�s<�(C���欮��U������y�����
�P�v_<�5M zg�}�ѠfgA	I�h�~�*�Ck�Z�y��L�7N+?ۥS^#�*)�E�T���,���4j�Wok�@��1�'4~
endstream
```

**Comment by patrickhoefler** [comment]
Hey @jamesone, thanks for raising this issue! 🙂

> Could the library include a timestamp?

You are absolutely correct:

```
❯ exiftool -all Dockerfile.pdf
ExifTool Version Number         : 12.40
File Name                       : Dockerfile.pdf
[...]
Page Count                      : 1
Producer                        : cairo 1.17.6 (https://cairographics.org)
Create Date                     : 2023:04:17 20:23:55Z
```

Unfortunately I am not aware of a way to tell `graphviz` not to include any metadata when generating the PDF via the `cairo` renderer.

To make things worse, it seems to be anything but trivial to remove PDF metadata after it's been created. `exiftool`, for example, [intentionally does not include this functionality](https://exiftool.org/forum/index.php?topic=3943.msg54629#msg54629).

In my quick preliminary tests, [mat2](https://0xacab.org/jvoisin/mat2)'s `--lightweight` mode looked promising:

```
❯ mat2 --lightweight --verbose Dockerfile.pdf
DEBUG: Cleaning Dockerfile.pdf…
INFO: Rendering page 1/1
```

Unfortunately, including `mat2` more than doubles the size of the Ubuntu-based container image, and on Alpine it's so far only available on Edge in the `testing` repo.

Anyway, I hope this information helps, and any ideas how to improve the situation are always more than welcome 🙂

**Comment by jamesone** [comment]
Thanks a lot, I appreciate your instant reply on this @patrickhoefler At this rate I can configure my dockerfilegraph script to run in a git commit hook whenever the Dockerfile has a change. This should be able to handle **this issue**. I will close this as it's quite clear that it's not trivial and that there are ways around it (i.e. like the one I explained).
|
