### ISSUE TITLE
Multiple --mount=from=* seem unsupported

### ISSUE THREAD

**Issue by iluminae** [patrickhoefler/dockerfilegraph#422]
Considering the following reproduction:
```dockerfile
FROM docker.io/library/alpine:latest AS base
RUN touch base

FROM base AS base2
RUN touch base2

FROM base AS base3
RUN touch base3

FROM base AS base4
RUN touch base4

FROM base
RUN --mount=from=base2,target=/base2 \
    --mount=from=base3,target=/base3 \
    --mount=from=base4,target=/base4 \
    cp base*/* .
RUN ls base*
```
the final dag rendered only shows one of the --mount-from connections.
![Dockerfile](https://github.com/patrickhoefler/dockerfilegraph/assets/22092713/74af439f-3ed4-4f24-b4f3-8c58125327ae)

**Comment by patrickhoefler** [comment]
Hey @iluminae,

thank you very much for your excellent bug report, much appreciated!

As you've probably seen, the fix is already being worked on and should land soon.
