### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by zevisert** [patrickhoefler/dockerfilegraph#46]
The output file could use a legend for the arrow types! I know they're documented in the readme, but having them embedded / on hand would be great!

Just came across this library 5 minutes ago - the `docker run` example worked perfectly for me, thank you!

**Comment by patrickhoefler** [comment]
Hey @zevisert,

thanks for your kind works, much appreciated! Also, I'm happy that it's working for you 🙂 

I just finished #47 – could you take a look and let me know if this is what you had in mind?

**Comment by zevisert** [comment]
Impressive turn around! The example you've got in #47 looks exactly like I was hoping for! Thank you!

**Comment by patrickhoefler** [comment]
I just released [v0.7.0](https://github.com/patrickhoefler/dockerfilegraph/releases/tag/v0.7.0) which includes the legend flag 🙂

**Comment by zevisert** [comment]
Thanks again!
